---
#- name: download Oracle JDK 8
#  get_url: 
#    url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
#    dest: /root/soft
#    headers: "Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'"
#    validate_certs: no
#    checksum: "sha256: 3d1e8cc66f4fd77acef6093329d5dd95bd06e4a03926c52df794f311a0c093f8"
- name: Copy jdk8 installer
  copy: 
    src: "{{role_path}}/files/jdk-8u144-linux-x64.rpm"
#    src: "{{role_path}}/files/jdk-8u131-linux-x64.rpm"
    dest: "{{ work_dir }}"
- name: Install JDK8
  yum:
    name: "{{ work_dir }}/jdk-8u144-linux-x64.rpm"
    state: present
  become: yes
