---
- name: Service start Jenkins
  service: 
    name: jenkins
    state: started
    enabled: yes
  register: jenkins_service
- name: Wait for jenkins up
  include: wait_for_jenkins_up.yml
  when: jenkins_service.changed

